services:
  web:
    build:
      dockerfile: DockerFile
      context: .
    ports:
      - 8000:8000
  database:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DATABSE: dj_db
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    