version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - ./logs:/app/logs  # Persistent logs
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
