# Generated by Django 5.1.7 on 2025-03-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_read", "To Read"),
                            ("reading", "Reading"),
                            ("read", "Read"),
                        ],
                        default="to_read",
                        max_length=20,
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReadingSessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("duration_minutes", models.PositiveBigIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
