# Generated by Django 5.1.7 on 2025-03-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReadingSessions",
            new_name="ReadingSession",
        ),
    ]
