services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: poetry run uvicorn booktracker.asgi:application --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
     - ./:/app/
    depends_on:
      - database
  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USERNAME -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
