version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: poetry run uvicorn booktracker.asgi:application --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    # Commented out the volumes part to avoid mounting issue
    # volumes:
    #   - ./:/app/

  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend_network

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
